# 
# GET USER 1 TASKS
GET http://127.0.0.1:8000/api/v1/tasks/tg_id/ HTTP/1.1

### 

# GET USER 2 TASKS
GET http://127.0.0.1:8000/api/v1/tasks/tg_id/ HTTP/1.1

### 

# UPDATE USER 1 TASK
PATCH http://127.0.0.1:8000/api/v1/tasks/tg_id/task_id/ HTTP/1.1
content-type: application/json

{
    "incorrect": 0,
    "correct": 10
}

###

# UPDATE USER 2 TASK
PATCH http://127.0.0.1:8000/api/v1/tasks/tg_id/task_id/ HTTP/1.1
content-type: application/json

{
    "incorrect": 0,
    "correct": 10
}

###

# GET USER 1 PROGRESS
GET http://127.0.0.1:8000/api/v1/progress/tg_id/ HTTP/1.1

### 

# GET USER 2 PROGRESS
GET http://127.0.0.1:8000/api/v1/progress/tg_id/ HTTP/1.1

###