# 
# GET USER 1 TASKS
GET http://127.0.0.1:8000/api/v1/tasks/user_id_1/ HTTP/1.1

### 

# GET USER 2 TASKS
GET http://127.0.0.1:8000/api/v1/tasks/user_id_2/ HTTP/1.1

### 


# GET USER 1 RESULTS
GET http://127.0.0.1:8000/api/v1/results/user_id_1/ HTTP/1.1

### 

# GET USER 2 RESULTS
GET http://127.0.0.1:8000/api/v1/results/user_id_2/ HTTP/1.1

###

# UPDATE USER 1 RESULTS
PATCH http://127.0.0.1:8000/api/v1/tasks/user_id_1/1/ HTTP/1.1
content-type: application/json

{
    "incorrect": 0,
    "correct": 10
}

###

# UPDATE USER 2 RESULTS
PATCH http://127.0.0.1:8000/api/v1/tasks/user_id_2/1/ HTTP/1.1
content-type: application/json

{
    "incorrect": 0,
    "correct": 10
}

###

# GET USER 1 STATS
GET http://127.0.0.1:8000/api/v1/progress/user_id_1/ HTTP/1.1

### 

# GET USER 2 STATS
GET http://127.0.0.1:8000/api/v1/progress/user_id_2/ HTTP/1.1

###