version: '3.8'

services:
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./new_nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/certificates:/etc/letsencrypt
      - ./certbot/webroot:/var/www/certbot
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/certificates:/etc/letsencrypt
      - ./certbot/webroot:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {your email} -d {your domain} --agree-tos