version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ../backend/
    # image: deevgeny/telegosha_backend:latest
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  
  bot:
    build: ../bot/
    # image: deevgeny/telegosha_bot:latest
    restart: always
    depends_on:
      - backend
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - backend
      - bot

volumes:
  static:
  media:
  database: