version: '3.8'

services:
  database:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  redis:
    image: redis:7.0-alpine
    restart: always

  backend:
    image: deevgeny/telegosha:backend-latest
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - database
      - redis
    env_file:
      - ./.env
  
  celery:
     image: deevgeny/telegosha:backend-latest
     restart: always
     volumes:
       - static:/app/static/
       - media:/app/media/
     depends_on:
       - backend
     env_file:
        - ./.env
     command: celery -A config worker -l INFO
  
  bot:
    image: deevgeny/telegosha:bot-latest
    restart: always
    volumes:
      - media:/app/media/
    depends_on:
      - backend
      - celery
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - backend
      - bot

volumes:
  static:
  media:
  database: