exclude: |
    (?x)^(
        venv/|
        .*/migrations/.*.py|
    )$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-yaml
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8