# Generated by Django 4.1.6 on 2023-02-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('intro', 'Знакомство'), ('learn', 'Запоминание'), ('test', 'Тест'), ('spell', 'Правописание')], help_text='Категория задания', max_length=8, verbose_name='Категория')),
                ('correct', models.PositiveSmallIntegerField(default=0, verbose_name='Верно')),
                ('incorrect', models.PositiveSmallIntegerField(default=0, verbose_name='Неверно')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('active', models.BooleanField(default=True, verbose_name='Активное')),
                ('passed', models.BooleanField(default=False, verbose_name='Пройдено')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите тему (категорию) слов', max_length=32, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, help_text='Краткое описание темы', max_length=128, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'темы',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Слово на иностранном языке', max_length=32, verbose_name='Слово')),
                ('translation', models.CharField(help_text='Значение на родном языке', max_length=32, verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'слово',
                'verbose_name_plural': 'слова',
                'ordering': ['origin'],
            },
        ),
    ]
