# Generated by Django 4.1.6 on 2023-02-04 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.PositiveSmallIntegerField(default=0, verbose_name='Верно')),
                ('incorrect', models.PositiveSmallIntegerField(default=0, verbose_name='Неверно')),
                ('passed', models.BooleanField(default=False, verbose_name='Пройдено')),
            ],
            options={
                'verbose_name': 'результат',
                'verbose_name_plural': 'результаты',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите тему (категорию) слов', max_length=150, unique=True, verbose_name='Тема')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Слово на иностранном языке', max_length=30, verbose_name='Слово')),
                ('translation', models.CharField(help_text='Значение на родном языке', max_length=30, verbose_name='Перевод')),
                ('topic', models.ForeignKey(help_text='Выберите тематику слова', on_delete=django.db.models.deletion.PROTECT, related_name='words', to='study.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'слово',
                'verbose_name_plural': 'слова',
                'ordering': ['origin'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('quiz', 'Тест'), ('spelling', 'Правописание')], help_text='Категория задания', max_length=8, verbose_name='Категория')),
                ('topic', models.ForeignKey(help_text='Выберите тему задачи', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='study.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
            },
        ),
    ]
