# Generated by Django 4.1.6 on 2023-02-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('quiz', 'Тест'), ('spelling', 'Правописание')], help_text='Категория упражнения', max_length=8, verbose_name='Категория')),
                ('topic', models.CharField(help_text='Тема упражнения', max_length=150, verbose_name='Тема')),
                ('description', models.CharField(blank=True, help_text='Описание задания, не более 150 символов.', max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'упражнение',
                'verbose_name_plural': 'упражнения',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Слово на иностранном языке', max_length=30, verbose_name='Слово')),
                ('translation', models.CharField(help_text='Значение на родном языке', max_length=30, verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'слово',
                'verbose_name_plural': 'слова',
                'ordering': ['origin'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Верно')),
                ('incorrect', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Неверно')),
                ('passed', models.BooleanField(default=False, editable=False, verbose_name='Пройдено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.exercise', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'задания',
            },
        ),
    ]
