# Generated by Django 4.1.6 on 2023-02-25 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='school_groups',
            field=models.ManyToManyField(help_text='Выбрать группы', related_name='topics', to='users.schoolgroup', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='topic',
            name='words',
            field=models.ManyToManyField(help_text='Выбрать минимум три слова', related_name='topics', to='study.word', verbose_name='Слова'),
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(help_text='Выберите тему задачи', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='study.topic', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(help_text='Выбрать ученика, чтобы назначить ему задание', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('name', 'description'), name='Тема с таким названием и описанием уже существует'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('topic', 'category', 'user'), name='Такое задание у пользователя уже существует'),
        ),
    ]
