# Generated by Django 4.1.6 on 2023-02-02 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='users',
            field=models.ManyToManyField(help_text='Выбрать учеников, чтобы назначить им упражнение', related_name='exercises', through='study.Task', to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='words',
            field=models.ManyToManyField(help_text='Добавить слова', related_name='exercises', to='study.word', verbose_name='Слова'),
        ),
    ]
